# Generated by Django 5.0.4 on 2024-05-20 07:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_lesson_link_to_the_video'),
        ('users', '0002_remove_user_username_user_avatar_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=datetime.datetime(2024, 5, 20, 15, 26, 32, 171002), verbose_name='Дата оплаты')),
                ('payment_amount', models.IntegerField(verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('Наличные', 'Наличные'), ('Перевод', 'Перевод')], default='Наличные', max_length=50, verbose_name='Метод оплаты')),
                ('paid_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Название урока')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('id',),
            },
        ),
    ]
