# Generated by Django 5.0.4 on 2024-05-20 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 15, 26, 40, 680393), verbose_name='Дата оплаты'),
        ),
    ]
