# Generated by Django 5.0.4 on 2024-05-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson_name',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
