# Generated by Django 5.0.4 on 2024-05-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_name',
            new_name='course',
        ),
    ]
