# Generated by Django 5.0.4 on 2024-05-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_rename_course_name_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_to_the_video',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
